[package]
name = "new_projects"
version = "0.1.0"
authors = ["Tuğçe Yalçın <yalntue.teyn@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
